apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-personhendelse
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: "{{ image }}"
  ingresses:
    - https://familie-ef-personhendelse.intern.dev.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      memory: 768Mi
    requests:
      memory: 256Mi
      cpu: 20m
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "59865891-62a0-4fe3-b282-2e38210d1fbb" # teamfamilie-ef-forvaltning
          - id: "928636f4-fd0d-4149-978e-a6fb68bb19de" # prosessering.rolle - (0000-GA-STDAPPS)
        extra:
          - "NAVident"
          - "azp_name"
      replyURLs:
        - "https://familie-ef-personhendelse.intern.dev.nav.no/swagger-ui/oauth2-redirect.html"
      singlePageApplication: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak
        - application: familie-prosessering
        - application: familie-prosessering-lokal
    outbound:
      rules:
        - application: familie-ef-sak
        - application: familie-ef-sak-lokal
      external:
        - host: kafka-schema-registry.nais-q.adeo.no
        - host: pdl-api.dev-fss-pub.nais.io
        - host: familie-integrasjoner.dev-fss-pub.nais.io
        - host: ikomp-q2.dev-fss-pub.nais.io
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        tier: db-g1-small
        cascadingDelete: false
        name: familie-ef-personhendelse-14
        databases:
          - name: familie-ef-personhendelse-14
            envVarPrefix: DB
  leaderElection: true
