apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-personhendelse
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: "{{ image }}"
  ingresses:
    - https://familie-ef-personhendelse.intern.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      memory: 768Mi
    requests:
      memory: 256Mi
      cpu: 50m
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak
    outbound:
      rules:
        - application: familie-ef-sak
        - application: familie-ef-proxy
          namespace: teamfamilie
          cluster: prod-fss
      external:
        - host: kafka-schema-registry.nais.adeo.no
        - host: pdl-api.prod-fss-pub.nais.io
        - host: familie-integrasjoner.prod-fss-pub.nais.io
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_14 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        diskAutoresize: true
        tier: db-g1-small
        cascadingDelete: false
        databases:
          - name: familie-ef-personhendelse
            envVarPrefix: DB
  leaderElection: true
